# Starting numpy 

### steps that might come handy
- B -> add cell
- Y/M -> code or markDown as u need
- Enter ->into edit mode
- ESc -> into commmand mode
- B/A -> below or Above cell create 
- SHift+Enter ->done with a cell block 

### creating arrays

In [10]:
import numpy as np

#arrays 
singleDim=np.array([1,2,3])
matrix=np.array([[1,2,3],[2,5,6]])
tensor=np.array([[[1,2,3],[2,5,6]],
                 [[1,2,3],[2,5,6]],
                 [[1,2,3],[2,5,6]]])

print(tensor)
# With initial values
np.zeros((2, 3))         # 2x3 array of 0s
np.ones((3, 3))          # 3x3 array of 1s
np.full((2, 2), 7)       # 2x2 array with 7s
np.eye(3)                # 3x3 Identity Matrix
np.random.rand(2, 2)     # Random floats [0,1)
np.random.randint(0, 10, (3, 3))  # Random ints

## imp one arange and linspace
print(np.arange(0,10,2)) # ps increment val at end
print("linspaces : \n",np.linspace(5,9.5,10))
#ending point also counts so calculate ending properly
# exactly distributed proper 10 sampes on that range


[[[1 2 3]
  [2 5 6]]

 [[1 2 3]
  [2 5 6]]

 [[1 2 3]
  [2 5 6]]]
[0 2 4 6 8]
linspaces : 
 [5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


### Time Comparison Numpy(c++) vs usual python array

In [3]:
import time 

initialTime=time.time()

pythonArray=[i*2 for i in range(10000000)]
# print(pythonArray)
print("\n Python raw operation time :",time.time()-initialTime)

initialTime2=time.time()
numpyArray=np.arange(10000000)*2
print("\n Numpy operation time:",time.time()-initialTime2)

print("\n Numpy is ",(time.time()-initialTime)/(time.time()-initialTime2)," times fast af")




 Python raw operation time : 0.7336580753326416

 Numpy operation time: 0.03741621971130371

 Numpy is  20.608022429668335  times fast af


### array attributes

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.ndim         # Number of dimensions
arr.shape        # Shape of array
arr.size         # Total number of elements
arr.dtype        # Data type
arr.itemsize     # Size of each item (bytes)
arr.nbytes       # Total bytes

print(np.arange(0,21)) #non inclusive

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


### indexing

In [66]:
mat=np.array([[1,2,3],[2,5,6],[2,5,6]])

mat[1,2] # row 1 and col 2
print(mat[:,1]) #all rows col1 
print(mat[1,:]) #all cols row1
print(mat[0:2,1:3]) #slicing sub matrix 



[2 5 5]
[2 5 6]
[[2 3]
 [5 6]]


### Operations

In [67]:
mat=np.array([[1,2,3],[2,5,6],[2,5,6]])
mat[:,2]=[7,8,9] #changing values of coloumn 3rd
print(mat)

copied=mat.copy()
# print(copied)

mat.reshape((1,-1)) # for infer use negative no zero allowed
print("Reshaped",mat)
copied.flatten()
print("flattened",copied)




[[1 2 7]
 [2 5 8]
 [2 5 9]]
Reshaped [[1 2 7]
 [2 5 8]
 [2 5 9]]
flattened [[1 2 7]
 [2 5 8]
 [2 5 9]]




```python
a = np.array([[1, 2, 3]])   # Shape: (1, 3) → 1 row, 3 columns
b = np.array([[1], [2], [3]])  # Shape: (3, 1) → 3 rows, 1 column
```

---


```python
a + b
```

NumPy tries to **"stretch" or broadcast** the shapes so they match for element-wise addition.

---

### 🔄 Step-by-step shape alignment:

* `a`: shape **(1, 3)**
  ➜ 1 row with 3 columns: `[1 2 3]`

* `b`: shape **(3, 1)**
  ➜ 3 rows, each with 1 column:

  ```
  [1]
  [2]
  [3]
  ```

➡️ NumPy broadcasts `a` down to 3 rows
➡️ NumPy broadcasts `b` across to 3 columns

Now both act like a **(3, 3)** shape:

```plaintext
a broadcasted:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

b broadcasted:
[[1 1 1]
 [2 2 2]
 [3 3 3]]
```

Now add them:

```plaintext
[[1+1 2+1 3+1]   → [2 3 4]
 [1+2 2+2 3+2]   → [3 4 5]
 [1+3 2+3 3+3]]  → [4 5 6]
```

➡️ Final output:

```python
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])
```

---

In [68]:
#broadcasting

a=np.array([1,2,3,4,5,6,7]) # shape (1,7)
b=np.array([[1],[2],[3],[4],[5],[6],[7]]) # shape(7,1)
print("dimension strechted array\n ",a+b)

dimension strechted array
  [[ 2  3  4  5  6  7  8]
 [ 3  4  5  6  7  8  9]
 [ 4  5  6  7  8  9 10]
 [ 5  6  7  8  9 10 11]
 [ 6  7  8  9 10 11 12]
 [ 7  8  9 10 11 12 13]
 [ 8  9 10 11 12 13 14]]


### Mathematical operations

In [69]:
a=np.array([1,2,3,4,5,6,7,8,90])
b=np.array([1,2,3,4,5,6,7,8,1])

print(a+b) #element wise addition
print(np.add(a,b)) #same element wise
print(np.dot(a,b),a*b) # dot prod or mat prod  , element wise multiplication ,np.cross(a,b)

print(np.mean(a),np.sin(a),np.max(a))
print(np.sin(np.radians(90))) #gotta convert to radians


#array stacking
c=np.vstack([a,b]) #vertical stack
d=np.hstack([a,b]) #horizontal stack

print(c,d);


[ 2  4  6  8 10 12 14 16 91]
[ 2  4  6  8 10 12 14 16 91]
294 [ 1  4  9 16 25 36 49 64 90]
14.0 [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.89399666] 90
1.0
[[ 1  2  3  4  5  6  7  8 90]
 [ 1  2  3  4  5  6  7  8  1]] [ 1  2  3  4  5  6  7  8 90  1  2  3  4  5  6  7  8  1]


### Masking boolean
 Basically  making an array of [True,False,False,True]
 And returning element that r true to that condition 
 A fitering method more likely

In [70]:
a =np.array([1,2,3,4,5,6,7,8,8,9])
mask=a>2
a[mask]
print(a[mask])



[3 4 5 6 7 8 8 9]


### Randoms 

In [71]:
import random #python raw

print(random.randint(1,20))
print(random.random()) #float shit

chocies=[1,2,5,677,8,4,32,6,8,84,23,6];
print(random.choice(chocies)) #interesting mmmh
random.shuffle(chocies) # returns nothing tho
print(chocies)


np.random.seed(0)
print(np.random.randint(5))
print(np.random.randn(3,3)) #including neg
# of int vals
print(np.random.randint(1,10,size=(2,2)))
#generating random array bruh

print(np.random.rand(2,3))


13
0.9324325566689802
8
[4, 677, 32, 6, 1, 8, 8, 6, 2, 5, 84, 23]
4
[[ 1.12279492  0.30280522  0.07085926]
 [ 0.07304142 -1.42232584  1.52006949]
 [-0.29139398 -0.13309028 -0.1730696 ]]
[[8 8]
 [9 2]]
[[0.92559664 0.07103606 0.0871293 ]
 [0.0202184  0.83261985 0.77815675]]


### Sorting & Searching

In [77]:
arr=np.array([1,2,4,56,7,8,9,9])
# np.sort(arr)

print(np.argsort(arr)) # returns auukaaad
print(np.where(arr==9))
print(np.count_nonzero(arr>8))


[0 1 2 4 5 6 7 3]
(array([6, 7]),)
3


### Linear Algebra 

In [82]:
arr=np.array([[10, 20], [30, 40], [50, 60]])

element_first=np.array([1,0])
element_second=np.array([1,1])

print(arr[element_first,element_second])

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])


# linalg 
print(np.matmul(a,b)) #matrix multiplication
print(np.linalg.inv(a)) #inverse?
print(np.linalg.det(np.linalg.matmul(a,b)))
#eigenvectors 
print(np.linalg.eig(a))


[40 20]
[[ 4  4]
 [10  8]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-7.999999999999998
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


### File saving nd Loading

In [88]:
a=np.arange(100)

np.save('array.npy',a) #ofc in cwd 
# .npy .npz
# .csv .txt readable
loaded=np.load('array.npy')
# print(loaded)

np.savetxt('data.csv', a, delimiter=',')
loaded2 = np.loadtxt('data.csv', delimiter=',')
print(loaded2)




[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]
